<?php
/**
 * Additional active industry pack stubs for Industry Profile primary/secondary selectors.
 * Minimal schema (industry-pack-schema.md): selection and overlays; detailed CTA/LPagery refs live in full packs or bundles.
 *
 * @package AIOPageBuilder
 */

declare( strict_types=1 );

defined( 'ABSPATH' ) || exit;

return array(
	array(
		'industry_key'   => 'healthcare_medical',
		'name'           => 'Healthcare — medical practice',
		'summary'        => 'Clinics and medical groups: appointments, services, providers, HIPAA-aware trust patterns.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'dental',
		'name'           => 'Dental',
		'summary'        => 'Dental practices: family and cosmetic dentistry, insurance and financing, booking-first CTAs.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'veterinary',
		'name'           => 'Veterinary',
		'summary'        => 'Animal clinics and hospitals: urgent care, wellness plans, boarding and grooming.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'mental_health',
		'name'           => 'Mental health & counseling',
		'summary'        => 'Therapists and counseling practices: intake, modalities, telehealth, discreet contact paths.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'legal_services',
		'name'           => 'Legal services',
		'summary'        => 'Law firms: practice areas, case intake, attorney bios, consultation requests.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'accounting',
		'name'           => 'Accounting & bookkeeping',
		'summary'        => 'CPA and bookkeeping firms: tax, payroll, advisory, client onboarding.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'financial_advisory',
		'name'           => 'Financial advisory',
		'summary'        => 'Wealth and financial advisors: planning, disclosures, seminar and webinar CTAs.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'insurance_agency',
		'name'           => 'Insurance agency',
		'summary'        => 'Independent agencies: quotes, policy types, local service area and carrier trust.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'real_estate_commercial',
		'name'           => 'Commercial real estate',
		'summary'        => 'CRE brokers and advisors: listings, investment thesis, tenant and landlord flows.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'property_management',
		'name'           => 'Property management',
		'summary'        => 'PM companies: owner and resident portals, maintenance, leasing funnels.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'restaurant',
		'name'           => 'Restaurant',
		'summary'        => 'Restaurants: menus, reservations, ordering, location and hours emphasis.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'bar_nightlife',
		'name'           => 'Bar & nightlife',
		'summary'        => 'Bars and venues: events, dress code, bookings, entertainment calendars.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'hospitality_lodging',
		'name'           => 'Hospitality & lodging',
		'summary'        => 'Hotels, B&Bs, and short-term rentals: booking, amenities, local guides.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'retail_ecommerce',
		'name'           => 'Retail & e-commerce',
		'summary'        => 'Product-led retail: catalog, shipping, returns, promotions, and trust badges.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'saas_b2b',
		'name'           => 'SaaS — B2B',
		'summary'        => 'B2B software: product tiers, demos, security and compliance proof, ROI framing.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'it_services',
		'name'           => 'IT & managed services',
		'summary'        => 'MSP and IT services: SLAs, support tiers, stack integrations, onboarding.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'manufacturing',
		'name'           => 'Manufacturing',
		'summary'        => 'Industrial and light manufacturing: capabilities, certifications, RFQs, distributor flows.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'construction_general',
		'name'           => 'Construction — general',
		'summary'        => 'General contractors: projects, safety, bids, warranties, service areas.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'architecture',
		'name'           => 'Architecture & design',
		'summary'        => 'Architecture and interior design studios: portfolio, process, consultations.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'engineering',
		'name'           => 'Engineering services',
		'summary'        => 'Civil, MEP, and specialty engineering: proposals, qualifications, compliance.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'nonprofit',
		'name'           => 'Nonprofit',
		'summary'        => 'Charities and NGOs: mission, impact, donate and volunteer journeys, transparency.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'education_k12',
		'name'           => 'Education — K–12',
		'summary'        => 'Schools and districts: enrollment, calendars, athletics, parent communication.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'higher_education',
		'name'           => 'Higher education',
		'summary'        => 'Colleges and programs: admissions, degrees, research, campus life.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'childcare',
		'name'           => 'Childcare & early learning',
		'summary'        => 'Daycares and preschools: programs, licensing trust, tours and waitlists.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'fitness_gym',
		'name'           => 'Fitness & gym',
		'summary'        => 'Gyms and studios: memberships, classes, trainers, trials.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'sports_recreation',
		'name'           => 'Sports & recreation',
		'summary'        => 'Leagues, clubs, and facilities: schedules, registration, sponsorships.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'automotive_repair',
		'name'           => 'Automotive — repair',
		'summary'        => 'Auto repair shops: services, diagnostics, fleet, appointments.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'automotive_dealer',
		'name'           => 'Automotive — dealership',
		'summary'        => 'Dealers: inventory, financing, test drives, trade-ins.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'beauty_salon',
		'name'           => 'Beauty — salon',
		'summary'        => 'Hair salons: stylists, services, booking, retail add-ons.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'spa_wellness',
		'name'           => 'Spa & wellness',
		'summary'        => 'Spas and med-spa adjacent: treatments, packages, memberships.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'hvac',
		'name'           => 'HVAC',
		'summary'        => 'Heating and cooling contractors: maintenance plans, replacements, emergency service.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'electrical_contractor',
		'name'           => 'Electrical contractor',
		'summary'        => 'Residential and commercial electrical: panels, EV, safety certifications.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'landscaping',
		'name'           => 'Landscaping & lawn',
		'summary'        => 'Landscape design and maintenance: seasonal plans, irrigation, hardscaping.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'roofing',
		'name'           => 'Roofing',
		'summary'        => 'Roofing contractors: inspections, storm response, warranties, financing.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'pest_control',
		'name'           => 'Pest control',
		'summary'        => 'Pest and termite services: plans, guarantees, seasonal treatments.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'cleaning_services',
		'name'           => 'Cleaning services',
		'summary'        => 'Residential and commercial cleaning: recurring service, deep clean, quotes.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'photography',
		'name'           => 'Photography',
		'summary'        => 'Photo studios and freelancers: portfolios, packages, booking, print sales.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'wedding_events',
		'name'           => 'Weddings & events',
		'summary'        => 'Event planners and venues: packages, galleries, inquiry funnels.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'marketing_agency',
		'name'           => 'Marketing agency',
		'summary'        => 'Creative and performance agencies: case studies, retainers, audits, contact.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'staffing_recruiting',
		'name'           => 'Staffing & recruiting',
		'summary'        => 'Staffing firms: job seeker and employer flows, industries served, compliance.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'logistics_shipping',
		'name'           => 'Logistics & shipping',
		'summary'        => '3PL and carriers: lanes, SLAs, tracking, freight quotes.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'agriculture',
		'name'           => 'Agriculture',
		'summary'        => 'Farms and ag services: products, sustainability, wholesale and direct.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'energy_utilities',
		'name'           => 'Energy & utilities',
		'summary'        => 'Solar, efficiency, and utility-adjacent services: savings calculators, incentives.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'government_public',
		'name'           => 'Government & public sector',
		'summary'        => 'Public-facing agencies: services, accessibility, forms, multilingual needs.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
	array(
		'industry_key'   => 'media_publishing',
		'name'           => 'Media & publishing',
		'summary'        => 'Publishers and creators: subscriptions, paywalls, editorial cadence, newsletters.',
		'status'         => 'active',
		'version_marker' => '1',
		'metadata'       => array( 'catalog' => 'verticals' ),
	),
);
